[package]
name = "simple-version"
version = "2.1.0"
edition = "2021"
authors = ["Park JiSoo <cherryjeesoo@gmail.com>"]
description = "The easiest way to manage versions in rust."
license = "MIT"

[dependencies]
# No dependencies